// <auto-generated />
using System;
using Examine2DSerialization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examine2DSerialization.Migrations
{
    [DbContext(typeof(Examine2DContext))]
    partial class Examine2DContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Examine2DSerialization.Entities.BoundaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundaryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Boundaries", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.MaterialPropertiesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Density")
                        .HasColumnType("REAL");

                    b.Property<double?>("E1")
                        .HasColumnType("REAL");

                    b.Property<double?>("E2")
                        .HasColumnType("REAL");

                    b.Property<double?>("G12")
                        .HasColumnType("REAL");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Nu12")
                        .HasColumnType("REAL");

                    b.Property<double?>("Nu23")
                        .HasColumnType("REAL");

                    b.Property<double?>("PoissonRatio")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("YoungModulus")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("MaterialProperties", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.QueryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Queries", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.QueryPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("QueryId", "Order");

                    b.ToTable("QueryPoints", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.StrengthCriterionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("A")
                        .HasColumnType("REAL");

                    b.Property<double?>("Cohesion")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("FrictionAngle")
                        .HasColumnType("REAL");

                    b.Property<double?>("Mb")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("S")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sci")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("StrengthCriteria", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.StressGridEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxX")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxY")
                        .HasColumnType("REAL");

                    b.Property<double>("MinX")
                        .HasColumnType("REAL");

                    b.Property<double>("MinY")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("XPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("StressGrids", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.VertexEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoundaryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BoundaryId", "Order");

                    b.ToTable("Vertices", (string)null);
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.BoundaryEntity", b =>
                {
                    b.HasOne("Examine2DSerialization.Entities.ProjectEntity", "Project")
                        .WithMany("Boundaries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.MaterialPropertiesEntity", b =>
                {
                    b.HasOne("Examine2DSerialization.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.QueryEntity", b =>
                {
                    b.HasOne("Examine2DSerialization.Entities.ProjectEntity", "Project")
                        .WithMany("Queries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.QueryPointEntity", b =>
                {
                    b.HasOne("Examine2DSerialization.Entities.QueryEntity", "Query")
                        .WithMany("Points")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.StrengthCriterionEntity", b =>
                {
                    b.HasOne("Examine2DSerialization.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.StressGridEntity", b =>
                {
                    b.HasOne("Examine2DSerialization.Entities.ProjectEntity", "Project")
                        .WithMany("StressGrids")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.VertexEntity", b =>
                {
                    b.HasOne("Examine2DSerialization.Entities.BoundaryEntity", "Boundary")
                        .WithMany("Vertices")
                        .HasForeignKey("BoundaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boundary");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.BoundaryEntity", b =>
                {
                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Boundaries");

                    b.Navigation("Queries");

                    b.Navigation("StressGrids");
                });

            modelBuilder.Entity("Examine2DSerialization.Entities.QueryEntity", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
